[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./script/payloads"}]
remappings = [
    "ethereum-vault-connector/=lib/ethereum-vault-connector/src/",
    "evk-periphery/=lib/evk-periphery/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
